### ISSUE TITLE
Combine efforts?

### ISSUE THREAD

**Issue by leeper** [jeroenooms/travis#1]
Feel like joining in on this package instead of starting anew?

https://github.com/cloudyr/travisci

**Comment by jeroenooms** [comment]
Ah cool. I asked on twitter if anyone had done a travis client yet but no-one responded. Sure let's merge.

**Comment by leeper** [comment]
Great! Just sent you an invite. I already had an issue (https://github.com/cloudyr/travisci/issues/3) open for the encryption aspect, which it looks like you have a good handle on here, so feel free to merge in however you see fit.
